sudo: required
language: node_js
node_js:
  - 8
branches:
  only:
    - master
install:
  - npm install -g firebase-tools
  - npm install
  - cd functions
  - npm install
  - cd ../
script:
  - npm run build
after_success:
  - firebase deploy --non-interactive --token $FIREBASE_TOKEN